name: Gettext updates

on:
  push:
    branches: [main]

jobs:
  gettext_flatpak:
    name: Gettext Flatpak
    runs-on: ubuntu-latest

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-46
      options: --privileged

    steps:
    - name: Install git, python3-git and jq
      run: |
        dnf -y install git jq python3-GitPython

    - name: Clone repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GIT_USER_TOKEN }}

    - name: Configure Git
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - uses: elementary/actions/gettext-flatpak@main
      with:
        manifest-path: 'com.github.ryonakano.pinit.yml'
        repository-url: 'https://dl.flathub.org/repo/flathub.flatpakrepo'
        repository-name: 'flathub'
