name: CI

on: [pull_request]

jobs:
  Flatpak:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false

    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-43
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install QEMU
        if: ${{ matrix.arch != 'x86_64' }}
        run: |
          dnf -y install docker
      - name: Set up QEMU for aarch64 emulation
        if: ${{ matrix.arch != 'x86_64' }}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v5
        with:
          bundle: pinit.flatpak
          manifest-path: com.github.ryonakano.pinit.yml
          run-tests: true
          cache-key: "flatpak-builder-${{ github.sha }}"
          arch: ${{ matrix.arch }}

  Lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: valalang/lint
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: io.elementary.vala-lint -d .
